/**
 * Verified assessment cases. Currently empty, deliberately and visibly.
 *
 * Nothing synthetic belongs here. A case generated by running this code and
 * recording what it said would pass forever while proving nothing, and would
 * be indistinguishable from a real one six months later.
 *
 * Where to get real ones, roughly in order of how much they are worth:
 *
 *   1. The Begutachtungs-Richtlinien (BRi) themselves. They carry worked
 *      examples, and they come from the body that does the assessing.
 *      https://md-bund.de/fileadmin/dokumente/Publikationen/SPV/Begutachtungsgrundlagen/
 *   2. Case studies published by Sozialverband VdK and the BIVA-Pflegeschutzbund,
 *      often written up around a successful objection, which means the corrected
 *      grade is stated.
 *   3. Pilot households, once a Pflegestützpunkt or a Wohlfahrtsverband is
 *      running one. When a family's Bescheid arrives, that is a labelled case,
 *      and asking for it is the single most valuable thing a pilot produces.
 *      Ask with consent, record no names, and keep only the numbers.
 *
 * Ten cases would tell you more about whether this product is correct than
 * anything else on the roadmap.
 */

import type { GutachtenCase } from './types';

export const GUTACHTEN_CASES: readonly GutachtenCase[] = [];
